#!/usr/bin/env php
<?php
use TJM\Component\Console\Application;
define('TJM_TBIN_DIR', __DIR__);
define('TJM_AUTOLOAD', TJM_TBIN_DIR . '/vendor/autoload.php');
if(!file_exists(TJM_AUTOLOAD)){
	echo "Initializing dependencies…\n";
	passthru('composer install -d ' . TJM_TBIN_DIR);
}
require_once(TJM_AUTOLOAD);
(new Application(TJM_TBIN_DIR . '/config/console.yml'))->run();
