#!/usr/bin/env php
<?php
use Symfony\Component\Console\Input\ArgvInput;
use TJM\Component\Console\Application;

$loader = __DIR__ . '/vendor/autoload.php';
if(!file_exists($loader)){
	echo "Initializing dependencies…\n";
	chdir(__DIR__);
	passthru('composer install');
}
$loader = require_once($loader);
$app = new Application(__DIR__ . '/config/console.yml');
$app->run(new ArgvInput());
