imports:
  - {resource: console.php}
services:
  TJM\TBin\Service\Shell:
    calls:
      - [addWhereAlias, [local, 'localhost']]
      - [addWhereAlias, [tmcom, 'tobymackenzie.com']]
  TJM\TBin\Command\:
    autowire: true
    resource: '%paths.project%/src/Command'
    tags: ['console.command']
tjm_console:
  name: 'tbin'
  version: '0.1'
